# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'final' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for final
	pod 'SwiftyJSON', '~> 4.0'
  	pod "SwiftSpinner"
	pod 'IQKeyboardManagerSwift'
	pod 'KeychainSwift', '~> 20.0'
	pod 'Alamofire'

end
